import "./globals.css"; // Import global styles
import { Montserrat } from "next/font/google";
import type { Metadata } from "next";
import Header from "@/components/header/Header";

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--montserrat",
  weight: ["400", "600"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.variable}>
        <Header />

        {children}
      </body>
    </html>
  );
}
